version: '3.9'

services:
  proposta-db:
    image: postgres:alpine
    container_name: postgres-proposta
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: proposta
    ports:
      - "5432:5432"

  analise:
    image: 'zupacademy/analise-financeira'
    ports:
      - "9999:9999"
    environment:
      SERVER_PORT: 9999
      LOG_LEVEL: INFO
      URL_SISTEMA_CARTAO: http://contas:8888/api/cartoes

  contas:
    image: 'zupacademy/contas'
    ports:
      - "8888:8888"
    environment:
      SERVER_PORT: 8888
      LOG_LEVEL: INFO