server:
  servlet:
    context-path: /v1

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/proposta
    username: postgres
    password: password
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: false

# Expondo todos os endpoins disponíveis no actuator
management:
  endpoints:
    web:
      exposure:
        include: '*'

info:
  app:
    name: proposta

clients:
  analyze:
    url: http://localhost:9999/api/solicitacao
  account:
    url: http://localhost:8888/api