spring:
  profiles:
    active: ${APP_PROFILE}
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/proposta}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: false