#server:
#  servlet:
#    context-path: /v1

info:
  app:
    name: proposta

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/proposta}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:18080/auth/realms/proposal}
          jwk-set-uri: ${KEYCLOAK_JWKS_URI:http://localhost:18080/auth/realms/proposal/protocol/openid-connect/certs}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: false

management:
  endpoints:
    web:
      exposure:
        include: '*'

clients:
  analyze:
    url: ${ANALYZE_API_URL:http://localhost:9999/api/solicitacao}
  account:
    url: ${ACCOUNTS_API_URL:http://localhost:8888/api}